export enum LoanStatus {
  DISPONIVEL = 'DISPONIVEL',
  EMPRESTADO = 'EMPRESTADO',
  FINALIZADO_DENTRO_DO_PRAZO = 'FINALIZADO_DENTRO_DO_PRAZO',
  FINALIZADO_FORA_DO_PRAZO = 'FINALIZADO_FORA_DO_PRAZO',
  ATRASADO = 'ATRASADO',
  PERDIDO = 'PERDIDO'
}
